### Login
POST {{url}}/token
Authorization: Basic {{username}} {{password}}

> {%
    client.global.set("auth_token", response.body);
%}

### Say hello
GET {{url}}/
Authorization: Bearer {{auth_token}}

### Get projects
GET {{url}}/api/projects
Authorization: Bearer {{auth_token}}

> {%
    client.global.set(
        "project_url",
        response.body["_embedded"]["projects"][0]["_links"]["self"]["href"]
    );
%}


### Get Project
GET {{project_url}}
Authorization: Bearer {{auth_token}}

### Create project
POST {{url}}/api/projects
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
}

### Root
GET {{url}}/api/
Authorization: Bearer {{auth_token}}
