### Login
POST {{url}}/token
Authorization: Basic {{username}} {{password}}

> {%
    client.global.set("auth_token", response.body)
%}

### Say hello
GET {{url}}/
Authorization: Bearer {{auth_token}}

### Get projects
GET {{url}}/api/projects
Authorization: Bearer {{auth_token}}

### Create project
POST {{url}}/api/projects
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
}

### Root
GET {{url}}/api/
Authorization: Bearer {{auth_token}}
