### Login
POST {{url}}/token
Authorization: Basic {{username}} {{password}}

> {%
    client.global.set("auth_token", response.body)
%}

### Say hello
GET {{url}}/hello
Authorization: Bearer {{auth_token}}

### Get projects
GET {{url}}/projects
Authorization: Bearer {{auth_token}}

### Root
GET {{url}}/
Authorization: Bearer {{auth_token}}
